### ISSUE TITLE
hass使用代理actions的url是本地IP地址

### ISSUE THREAD

**Issue by maybeloveu** [shaonianzhentan/ha_qqmail#1]
使用代理的环境，action地址是本地ip无法通过外网调用。希望能增加外网url配置。

**Comment by shaonianzhentan** [comment]
需要你在HA里配置外网地址

**Comment by maybeloveu** [comment]
ha配置了base_url，就不能在本地用ip访问，也是被逼的只能使用代理

**Comment by shaonianzhentan** [comment]
![image](https://user-images.githubusercontent.com/5294022/125181643-79d5cc80-e239-11eb-9066-30dc80cc1606.png)

建议配置外部URL
