### ISSUE TITLE
建议再增加action触发的时效性

### ISSUE THREAD

**Issue by maybeloveu** [shaonianzhentan/ha_qqmail#2]
建议判断连接uuid的时效性，比如十分钟内可触发，这样更安全一些。

**Comment by shaonianzhentan** [comment]
之前有这个设定

> 建议判断连接uuid的时效性，比如十分钟内可触发，这样更安全一些。

之前有这个功能，但是我用了一段时间，安全==不方便，所以就删掉了

每次重启都会生成不一样的URL地址，之前的会失效，所以还算安全吧😂

**Comment by maybeloveu** [comment]
但是重启后使用之前的连接虽然没有执行成功，但是提示还是触发事件成功
